### ISSUE TITLE
Компиляция!

### ISSUE THREAD

**Issue by maxsssssssss** [extremecodetv/ExtremeCodeOS#105]
Как скомпилировать ОС?

**Comment by Nikita-bunikido** [comment]
Пока целиком никак. По отдельности

**Comment by maxsssssssss** [comment]
Хммм. Ну ладно.

**Comment by Nikita-bunikido** [comment]
Можете например сначала терминал скомпилировать так: #102

**Comment by maxsssssssss** [comment]
Я сейчас пишу программу для компиляции ОС.
(P.S По отдельность.)

**Comment by maxsssssssss** [comment]
Как добавить свой код к проекту?

**Comment by Nikita-bunikido** [comment]
#108
