### ISSUE TITLE
Yobkiy Music

### ISSUE THREAD

**Issue by yosa12978** [extremecodetv/ExtremeCodeOS#117]
Добавить встроенный музыкальный плеер - Yobkiy Music

**Comment by maxsssssssss** [comment]
Класс!

**Comment by havr-desk** [comment]
Хз, музыкальный плеер - есть ли смысл в 2к21 (когда есть спотифаи и т.п.), а вот какой-нибудь видеоплеер забацать, чё бы и нет

Предупреждаю - я не профи, поэтому не удивляйтесь какому-то детскому коду. За вечерок с ютубом наляпал

https://github.com/havr-desk/multimedia.git

Как портировать на другие компы - ещё хз, не научился
