### ISSUE TITLE
Добавил интерпретатор современного языка PETOOH

### ISSUE THREAD

**Issue by Nikita-bunikido** [extremecodetv/ExtremeCodeOS#135]
#134

**Comment by pheianox** [comment]
Ару не магу

**Comment by Nikita-bunikido** [comment]
> Ару не магу

Значит работа удалась )

**Comment by yosa12978** [comment]
А он полный по тьюрингу?

**Comment by Nikita-bunikido** [comment]
> А он полный по тьюрингу?

Это диалект brainfuck. Соответственно да)

**Comment by pheianox** [comment]
> А он полный по тьюрингу?

ПРИОРА НОВАЯ, ТЮРНИГ ЕСТЬ.
