### ISSUE TITLE
src/kernel/Loader.c - Что это?

### ISSUE THREAD

**Issue by Nikita-bunikido** [extremecodetv/ExtremeCodeOS#138]
``` C
#include "stdio.h"
#include "string.h"
#include "stdlib.h"

int main(int argc, char** argv) {
    int input;

    printf("1. Run kernel.\n");
    printf("2. Run UI.\n");
    printf("3. Exit.\n");

    scanf("%d", &input);

    switch (input)
    {
        case 1:
            Run()
            break;
        
        case 2:
            printf("Sorry.\n");
            scanf("%d", &input);
            quit(0);
            break;
        
        case 3:
            quit(0);
            break;
    }
}

int Run() {

}
```

Функция run описана ниже, main его не видит, ошибка.
Если функцию переместить на верх то ошибка уйдёт,
но она всё равно ничего не делает.
В моей среде отсутствует функция quit(), тоже ошибка
После Run() не стоит ```;```, это вам не питон!

Файл с ошибками, и ничего не делает, либо пусть автор его исправит
либо пусть удалит.
P.S. Файл не соответствует ему же собственному readme

**Comment by Vano4ok** [comment]
Нет

**Comment by Nikita-bunikido** [comment]
> Нет

А можно поподробнее?

**Comment by Vano4ok** [comment]
Да шучу, зря быканул

**Comment by Nikita-bunikido** [comment]
Ага, ок

**Comment by maxsssssssss** [comment]
Да я это добавил по приколу :) Этот файл относится к #121.

**Comment by Nikita-bunikido** [comment]
> Да я это добавил по приколу :) Этот файл относится к #121. Ладно, если серьёзно то это временный файл. Я потом заменю его на нормальный.

Ок
