### ISSUE TITLE
Добавить игру на тренировку реакции для домохозяек

### ISSUE THREAD

**Issue by BlitDev** [extremecodetv/ExtremeCodeOS#199]
Я могу запилить эту игру на C#, норм идея?
Тренировка реакции очень важна для домохозяек.
И используя знания Биологии, генной инженерии, можно прийти к выводу: Что это никак нам не поможет.
Однако тренировка реакции поможет домохозяйкам научиться набирать текст со скоростью 2 кнопки в минуту, кроме прошлой 1 кнопки.

**Comment by BlitGaming** [comment]
Что лучше? .NET 6 и последующий компил в исполняемый, или .net Framework и mono?

**Comment by Suckston42** [comment]
Идея: добавить игру, где Линус Торвальдс будет стрелять надписью "Fuck You" в работников NVidia
