### ISSUE TITLE
Переписать всё на MSIL

### ISSUE THREAD

**Issue by Airkek** [extremecodetv/ExtremeCodeOS#21]
к черту фарш, он всё равно сгенерит MSIL код, давай сразу на IL

**Comment by Airkek** [comment]
а главное что останется дотнет!!!

**Comment by pheianox** [comment]
Microsoft? No, thanks.

**Comment by extremecodetv** [comment]
Не, ну наши лоулевел айкью задроты все равно будут кодить на иле, ну типа драйвера там бахать, тем более запрос уже был на портирование дров с винды.

Но мы как бы юзерфрендли для разработчиков, поэтому даем возможность использовать фарш
