### ISSUE TITLE
Слишком платформозависимый код ядра

### ISSUE THREAD

**Issue by supernova-III** [extremecodetv/ExtremeCodeOS#220]
Собственно, сабж. Что делать будем?

**Comment by supernova-III** [comment]
Мне придется созвать Комитет. Вы этого хотите?

**Comment by supernova-III** [comment]
Fixed.

**Comment by BlitDev** [comment]
А что собственно произошло? Коммитов даже не было. Как это **Fixed**

**Comment by supernova-III** [comment]
> А что собственно произошло? Коммитов даже не было. Как это **Fixed**

Не важно, я уже пофиксил.
