### ISSUE TITLE
Добавить магическое число 0x727 во все заголовки файлов

### ISSUE THREAD

**Issue by Airkek** [extremecodetv/ExtremeCodeOS#53]
Число 727 обладает целебным свойством. Еще в древние времена племя Вуду использовало число 727 как оберег, а нынче это число не только привлекает удачу, но и показывает высокий статус человека в обществе.
Также для положительного эффекта данного магического числа необходимо назвать секцию с выполняемым кодом .BlueZenith (вместо .text), а секцию .boot переименовать в .cookiezi

**Comment by nyan2d** [comment]
бан

**Comment by Airkek** [comment]
> бан

за что

**Comment by Airkek** [comment]
это прогрессивное и современное предложение

**Comment by extremecodetv** [comment]
Только магия вуду нам и поможет, больше не на что надеяться
Принято

**Comment by Ezhidzee** [comment]
это лучшее что я здесь видел
