### ISSUE TITLE
запретить джаву

### ISSUE THREAD

**Issue by yosa12978** [extremecodetv/ExtremeCodeOS#65]

**Comment by TheReactiveMouse** [comment]
Скажу так, если запретить Java то рухнет огромное кол-во приложений, а учитывая что дистрибутив рассчитан будет на пользователя то ему нужно будет играть в игры, а школьники в первую очередь заинтересуются майном или подобными играми на Java, поэтому нет смысла её запрещать, возможно, переписать/адаптировать, но не запрещать.

**Comment by yosa12978** [comment]
https://github.com/extremecodetv/ExtremeCodeOS/issues/48

**Comment by Airkek** [comment]
> Скажу так, если запретить Java то рухнет огромное кол-во приложений, а учитывая что дистрибутив рассчитан будет на пользователя то ему нужно будет играть в игры, а школьники в первую очередь заинтересуются майном или подобными играми на Java, поэтому нет смысла её запрещать, возможно, переписать/адаптировать, но не запрещать.

майн перепишем на F#, можно и джаву запретить после такого

**Comment by TheReactiveMouse** [comment]
> > Скажу так, если запретить Java то рухнет огромное кол-во приложений, а учитывая что дистрибутив рассчитан будет на пользователя то ему нужно будет играть в игры, а школьники в первую очередь заинтересуются майном или подобными играми на Java, поэтому нет смысла её запрещать, возможно, переписать/адаптировать, но не запрещать.
> 
> майн перепишем на F#, можно и джаву запретить после такого

лол, майн closed-source, и даже если вы будете переписывать его то напишите максимум 20-40% всего возможного функционала.

**Comment by Airkek** [comment]
> > > Скажу так, если запретить Java то рухнет огромное кол-во приложений, а учитывая что дистрибутив рассчитан будет на пользователя то ему нужно будет играть в игры, а школьники в первую очередь заинтересуются майном или подобными играми на Java, поэтому нет смысла её запрещать, возможно, переписать/адаптировать, но не запрещать.
> > 
> > 
> > майн перепишем на F#, можно и джаву запретить после такого
> 
> лол, майн closed-source, и даже если вы будете переписывать его то напишите максимум 20-40% всего возможного функционала.

лол чел ты не шаришь мы уже давно выкупили майнкрафт у майкрософта

**Comment by catman0745** [comment]
Поддерживаю

**Comment by draklowell** [comment]
Майн есть и на си
