### ISSUE TITLE
Extreme Studio Code

### ISSUE THREAD

**Issue by invizex** [extremecodetv/ExtremeCodeOS#80]
Создать эксклюзивную IDE для Yoptascript, JS и brainfuck  чтобы домохозяйки радовались хорошим ПО с нормальным GUI

**Comment by Nikita-bunikido** [comment]
С интерфейсом или в стиле Vim?

**Comment by Nikita-bunikido** [comment]
А как форматировать brainfuck?

**Comment by extremecodetv** [comment]
Тут нужен дедсек228, шобы на основе идеи замутил нам поддержку йопты
