### ISSUE TITLE
На какой платформе/технологии поддерживается GUI на ExtremeCodeOS?

### ISSUE THREAD

**Issue by Nikita-bunikido** [extremecodetv/ExtremeCodeOS#82]
Просто задача переписать все CLI приложения на CUI. Моя папка с играми
содержит пока только игры работающие в консоли. (Терминал ExtremeCodeOS
пока даже не может открывать бинарники)
Подходит ли RayLib в связке с С для GUI, или что вообще следует юзать?
Так что пока я займусь доработкой терминала

**Comment by extremecodetv** [comment]
Над терминалом можно сильно не упарываться, один хер потом его выпелим. Ну а по UI у нас золотой стандарт электрон, надо тупа кнопки стандартные сверстать и хуй забить

**Comment by Nikita-bunikido** [comment]
@extremecodetv а как же терминальные игры запускать, если выпилите?

**Comment by Nikita-bunikido** [comment]
А также есть тут что по делать со знаниями сишечки кроме терминала и игр?

**Comment by IAGrig** [comment]
> @extremecodetv а как же терминальные игры запускать, если выпилите?

Сделать им GUI
