### ISSUE TITLE
Добавить поддержку создать/удалить файл

### ISSUE THREAD

**Issue by pheianox** [extremecodetv/ExtremeCodeOS#87]
Ядру нужны новые команды, такие как `touch <filename>` и `rm <filename> или  rm *` для добавления или удаления (всех) файлов.

**Comment by Nikita-bunikido** [comment]
Могу реализовать

**Comment by pheianox** [comment]
Отлично!

**Comment by Nikita-bunikido** [comment]
Реализовал новые фичи.
Как же просто теперь дизайнить новые команды с новой архитектурой

**Comment by pheianox** [comment]
Согласен. Добовлять новые команды стало легче с новой архитектурой.
