### ISSUE TITLE
Вопрос к Линусу: UI дазайн 

### ISSUE THREAD

**Issue by ketsushiri** [extremecodetv/ExtremeCodeOS#90]
Будут ли какие-то общие стандарты по оформлению гуев? Какие-то обязательные для всех интерфейсов вещи? Конкретные предпочтительные фреймворки?
#82 
#84

**Comment by extremecodetv** [comment]
Ну нахуярьте там ченить, я хз. 
Нам все равно свои иксы с блекджеком надо будет делать. А пока перебьемся тем, что удобнее

**Comment by extremecodetv** [comment]
Вообще электрон по кайфичу, надо какой нить стандартный набор кнопок сверстать на джаваскрипте
